wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    clocks_a:
      colors:
        rows:
          even: "lightblue"
          odd: "white"
      enabled: true
      locations:
        Vancouver: "America/Vancouver"
        Melbourn: "Australia/Melbourne"
        Rajasthan: "Asia/Kolkata"
        Newyork: "America/New_York"
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      sort: "alphabetical"
      title: "Clocks A"
      type: "clocks"
    power:
      enabled: true
      position:
        top: 0
        left: 1
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
    uptime:
      args: [""]
      cmd: "uptime"
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 2
      refreshInterval: 30
      type: cmdrunner
    devto:
      enabled: true
      numberOfArticles: 10
      position:
        top: 2
        left: 0
        height: 1
        width: 2
      contentTag: "showdev"
      contentUsername: "victoravelar"
      contentState: "rising"
      refreshInterval: 15h
    hackernews:
      enabled: true
      numberOfStories: 10
      position:
        top: 1
        left: 0
        height: 1
        width: 2
      storyType: top
      refreshInterval: 15m
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 2
        left: 2
        height: 2
        width: 1
      refreshInterval: 10s
      showCPU: true
      showMem: true
      showSwp: true
    security:
      enabled: true
      position:
        top: 0
        left: 2
        height: 2
        width: 1
      refreshInterval: 1h
