" Options ---------- {{{

colorscheme elflord
set autoindent
set autoread
set backspace=indent,eol,start
set completeopt
set conceallevel=0
set cursorline
set cursorlineopt=number
set diffopt+=vertical
set expandtab
set fileencoding=utf-8
set hlsearch
set ignorecase
set incsearch
set iskeyword+=-
set lazyredraw
set nobackup
set nocompatible
set norelativenumber
set noshowmode
set noswapfile
set nowritebackup
set number
set numberwidth=4
set pumheight=10
set relativenumber
set scrolloff=4
set shiftwidth=2
set sidescrolloff=4
set signcolumn=yes
set smartcase
set smartindent
set smarttab
set softtabstop=4
set splitbelow
set splitright
set tabstop=2
set timeoutlen=1000
set undofile
set updatetime=300
set whichwrap+=<,>,[,],h,l
set wildmenu
set wildmode=full
set wildoptions=pum
set wrap
syntax on


" }}}


let mapleader = ' '

" keymaps ---------- {{{

inoremap jk <ESC>
nnoremap <leader>ev :vsplit $MYVIMRC<cr>
nnoremap <leader>eb :vsplit $HOME/.zshrc<cr>

" }}}

" Auto commands ---------- {{{

augroup vimsrc
   autocmd!
   autocmd BufWritePost .vimrc :source %
augroup END

augroup vim_ft
  autocmd!
  autocmd FileType vim setlocal foldmethod=marker
augroup END

" }}}
